steps:
      - name: 1. Descargar codigo
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependencias (Limpio)
        # Usamos 'npm install' para asegurar que se creen los node_modules
        run: npm install

      - name: 4. Ejecutar Tests
        # Esto llamará a tu script test.js
        run: npm test